knpu_oauth2_client:
    clients:
      google:
        type: google
        client_id: '%env(GOOGLE_OAUTH_ID)%'
        client_secret: '%env(GOOGLE_OAUTH_SECRET)%'
        redirect_route: connect_google_check
        redirect_params: {}